security:
    password_hashers:
        App\Entity\User: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: login

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            form_login:
                login_path: app_login
                check_path: app_login
                username_parameter: _login
                password_parameter: _password
                enable_csrf: true
                default_target_path: app_home
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                path: /
                always_remember_me: false
            logout:
                path: app_logout
                target: app_home

    access_control:
        - { path: ^/dashboard, roles: ROLE_USER }
        - { path: ^/organizations, roles: ROLE_USER }
        - { path: ^/contacts, roles: ROLE_USER }
        - { path: ^/calls, roles: ROLE_USER }
        - { path: ^/campaigns, roles: ROLE_USER }
